import type { Metadata } from "next";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { fontClassMap } from "@/lib/fonts";
import Header from "@/components/layouts/header";
import { getCurrentTheme } from "@/lib/current-theme";
import { getCurrentFont } from "@/lib/current-font";
import { getCurrentSeason } from "@/lib/current-season";
import ThemeProvider from "@/components/providers/theme-provider";
import Background from "@/components/layouts/background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const theme = await getCurrentTheme();
  const font = await getCurrentFont();
  const season = await getCurrentSeason();

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${fontClassMap[font]} antialiased ${season}`}>
        <NextIntlClientProvider>
          <ThemeProvider initialTheme={theme}>
            <Background />
            <Header />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
